name: Build and push Docker images
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Setup tailwind
        run: |
          npm install -D tailwindcss
          npm install -D @tailwindcss/typography

      - name: tailwindcss
        run: sh ./DistributedCodingCompetition.Web/tailwind.sh

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish ApiService
        run: dotnet publish ./DistributedCodingCompetition.ApiService -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/apiservice

      - name: Publish AuthService
        run: dotnet publish ./DistributedCodingCompetition.AuthService -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/authservice

      - name: Publish CodeExecution
        run: dotnet publish ./DistributedCodingCompetition.CodeExecution -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/codeexecution
      
      - name: Publish CodePersistence
        run: dotnet publish ./DistributedCodingCompetition.CodePersistence -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/codepersistence

      - name: Publish ExecRunner
        run: dotnet publish ./DistributedCodingCompetition.ExecRunner -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/execrunner

      - name: Publish Judge
        run: dotnet publish ./DistributedCodingCompetition.Judge -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/judge

      - name: Publish Leaderboard
        run: dotnet publish ./DistributedCodingCompetition.Leaderboard -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/leaderboard

      - name: Publish LiveLeaders
        run: dotnet publish ./DistributedCodingCompetition.LiveLeaders -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/liveleaders

      - name: Publish Web
        run: dotnet publish ./DistributedCodingCompetition.Web -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/web
     