name: Build and push Docker images
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Setup tailwind
        run: |
          npm install -D tailwindcss
          npm install -D @tailwindcss/typography

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: tailwindcss
        working-directory: ./DistributedCodingCompetition.Web
        run: sh ./tailwind-build.sh

      - name: Restore
        run: dotnet restore 

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish ApiService
        run: dotnet publish ./DistributedCodingCompetition.ApiService -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/apiservice

      - name: Publish AuthService
        run: dotnet publish ./DistributedCodingCompetition.AuthService -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/authservice 

      - name: Publish CodeExecution
        run: dotnet publish ./DistributedCodingCompetition.CodeExecution -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/codeexecution 

      - name: Publish CodePersistence
        run: dotnet publish ./DistributedCodingCompetition.CodePersistence -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/codepersistence 

      - name: Publish ExecRunner
        run: dotnet publish ./DistributedCodingCompetition.ExecRunner -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/execrunner

      - name: Publish Judge
        run: dotnet publish ./DistributedCodingCompetition.Judge -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/judge 

      - name: Publish Leaderboard
        run: dotnet publish ./DistributedCodingCompetition.Leaderboard -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/leaderboard 

      - name: Publish LiveLeaders
        run: dotnet publish ./DistributedCodingCompetition.LiveLeaders -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/liveleaders 

      - name: Publish Web
        run: dotnet publish ./DistributedCodingCompetition.Web -c Release --os linux --arch x64 /t:PublishContainer -o ./publish/web 

      - name: Push to docker Hub
        if: ${{ github.event_name == 'push' }}
        run: |
          docker tag distributedcodingcompetition-apiservice:latest ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-apiservice:latest
          docker tag distributedcodingcompetition-authservice:latest ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-authservice:latest
          docker tag distributedcodingcompetition-codeexecution:latest ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-codeexecution:latest
          docker tag distributedcodingcompetition-codepersistence:latest ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-codepersistence:latest
          docker tag distributedcodingcompetition-execrunner:latest ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-execrunner:latest
          docker tag distributedcodingcompetition-judge:latest ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-judge:latest
          docker tag distributedcodingcompetition-leaderboard:latest ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-leaderboard:latest
          docker tag distributedcodingcompetition-liveleaders:latest ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-liveleaders:latest
          docker tag distributedcodingcompetition-web:latest ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-web:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-apiservice:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-authservice:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-codeexecution:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-codepersistence:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-execrunner:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-judge:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-leaderboard:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-liveleaders:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/distributedcodingcompetition-web:latest
